<a href="https://colab.research.google.com/github/khoa2210/Hoc-Colab/blob/main/BT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [1]:
import numpy as np

In [5]:
#Code 
sample_1 = np.arange(-15, 27, 0.7)
sample_1

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [6]:
#Code
sample_2 = np.random.normal(loc = 2.7, scale = 1.20, size = 40)
sample_2

array([2.55635321, 4.82083321, 1.95778312, 2.80817823, 2.24907027,
       4.51477837, 2.73256423, 2.11452749, 2.31821105, 0.15954672,
       2.60969629, 1.82117268, 1.7670337 , 5.12034615, 3.80979849,
       3.96169371, 3.66502623, 3.19743236, 2.35023512, 3.05797281,
       2.77140766, 3.28958314, 2.66796605, 3.65285032, 1.05990396,
       1.51076843, 4.47627299, 1.15800301, 1.0629527 , 1.78532179,
       1.44471774, 2.02124556, 3.37069621, 3.16031052, 3.86953147,
       7.51617725, 1.61522595, 1.80790744, 0.96359663, 4.66888982])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [7]:
#Code
sample_3 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17)
sample_3

array(['Britain', 'Britain', 'Russia', 'Russia', 'Britain', 'Russia',
       'Russia', 'Russia', 'France', 'Britain', 'Singapore', 'Singapore',
       'Russia', 'France', 'Singapore', 'Britain', 'Viet Nam'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [8]:
#Code
sample_4 = np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 6, p = [0.1, 0.3, 0.2, 0.2,0.2])
print(sample_4)

['Britain' 'Britain' 'Britain' 'Viet Nam' 'Russia' 'Russia']


Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [9]:
from scipy import stats

In [10]:
#Code
sample_5 = stats.norm.rvs(loc = 12.7, scale = 2.6, size = 30)
sample_5

array([11.60957618, 11.36389708, 14.08684984, 14.78163359,  4.90173113,
       11.62936491, 14.9596276 , 12.01541259,  4.5940916 , 12.54872316,
       10.16152543, 12.06122802, 11.77859003, 13.47524478, 10.7850051 ,
       12.03856551, 11.81191801, 14.05124632, 11.44284907,  9.16878079,
       12.95882599, 11.52774034, 12.85626422, 14.21957783, 14.20153567,
        9.26545035,  6.6249482 , 12.8707781 , 13.7357525 , 11.93194094])

2. Hãy sinh một mẫu ngẫu nhiên theo phân phối Poisson

In [11]:
#Code
sample_6 = stats.poisson.rvs(loc=18,
                              mu=30,
                              size=10)
sample_6

array([43, 45, 44, 50, 41, 43, 53, 58, 58, 52])