<a href="https://colab.research.google.com/github/khoa2210/Hoc-Colab/blob/main/BtNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Khởi tạo Vecto ma trận 

In [16]:
import numpy as np
A = np.array([[6, 5], [8, -6]]) 
B = np.array([[9, -3], [2, 6]])

Các phép toán 


In [17]:
C = A + B
print(C) #tong ma tran a va b
E= A-B
print(E) #hieu ma tran a va bb
D = A.dot(B)
print(D) # tich ma tran a va b
print(A.transpose()) #chuyen vi ma tran a

[[15  2]
 [10  0]]
[[ -3   8]
 [  6 -12]]
[[ 64  12]
 [ 60 -60]]
[[ 6  8]
 [ 5 -6]]


Mảng giá trị mặc định (0 và 1)

In [30]:
# Mọi phần tử đều là 0
a = np.zeros( (2, 3) )
print(a)
# Mọi phần tử đều là 1
b = np.ones( (3, 3) )
print(b)
#ma trận đơn vị 
c = np.eye(4)
print(c)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Xuất các phần tử, cột, dòng của ma trận

In [31]:
print("A[0] =", A[0]) #xuất phần tử đầu tiên 
print("A[1] =", A[1]) # phần tử thứ 2
# Phần tử đầu tiên của hàng đầu tiên
print("A[0][0] =", A[0][0])

# Phần tử thứ 2 của hàng thứ 1
print("A[0][1] =", A[0][1])

# Phần tử cuối cùng của hàng cuối cùng
print("A[-1][-1] =", A[-1][-1])

print("A[:,0] =",A[:,0]) # Cột đầu tiên
print("A[:,1] =", A[:,1]) # Cột thứ 2
print("A[:,-1] =", A[:,-1]) # Cột cuối cùng 

A[0] = [6 5]
A[1] = [ 8 -6]
A[0][0] = 6
A[0][1] = 5
A[-1][-1] = -6
A[:,0] = [6 8]
A[:,1] = [ 5 -6]
A[:,-1] = [ 5 -6]


Cắt ma trận (chỉnh sửa ảnh )

In [33]:
x = np.array([[1, 4, 5, 12, 14], 
 [-5, 8, 9, 0, 17],
 [-6, 7, 11, 19, 21]])
print(x[:, 2:5]) # tất cả các hàng, cột 3 đến 5

[[ 5 12 14]
 [ 9  0 17]
 [11 19 21]]


Hàm max , min, average

In [35]:
e=np.max(x)
f=np.min(x)
g=np.average(x)
print(e)
print(f)
print(g)

21
-6
7.8
